# Conclusão {#conclusao}

```{=latex}
\begin{refsection}
```


\begin{epigrafe}
	\vspace*{\fill}
	\begin{flushright}
    \textit{``The boom years of the 1990s created a business atmosphere\\
    akin to a gold rush, and led many people to distort their business\\
    decisions, the results of which will weigh upon us for many years\\
    to come. Part of this change in business atmosphere was a decline\\
    in ethical standards, a decline in the belief in integrity, honesty,\\
    patience, and trust in business. A string of scandals affecting\\ 
    corporate boards, accounting firms, and mutual funds surfaced after\\
    the market dropped.''\\
    \cite[p. xiv]{shiller}}
	\end{flushright}
\end{epigrafe}

Conforme analisado ao longo dos capítulos anteriores, todas as evidências apontam 
que, dentro os diversos fatores, é a terra o problema central das crises 
habitacionais, seja quando se analisa a crise habitacional global, seja quando 
se analisa a crise habitacional crônica que vive o Brasil e outros países em 
desenvolvimento, que por sua vez é fortemente influenciada pela questão do 
financiamento. Isto não quer dizer que os outros fatores, como mão-de-obra, 
materiais de construção e infraestrutura não façam parte da solução do problema,
especialmente quando se trata dos países em desenvolvimento, como o Brasil, em
que a solução da crise necessariamente passa pelo aumento da oferta de moradias,
que deverão ser construídas em locais com infraestrura adequada e com material e
mão-de-obra adequados, diferentemente do que ocorre em pelo menos alguns dos 
países desenvolvidos, onde a crise habitacional se apresenta mais como um 
problema de distribuição de renda do que como um problema de falta de moradias
dignas para abrigar a população destes países.

Como mostrado no capítulo \@ref(historico), por questões estruturais que estão
além do escopo deste trabalho, durante boa parte do século XX a inflação
brasileira apresentava um comportamento anômalo, diferente do esperado,
elevando-se em períodos de baixa conjuntura e arrefecendo com o aquecimento da
Economia. A inflação, portanto, tinha um papel de incentivar as imobilizações, o
que fazia com que o preço da terra no Brasil se elevasse em períodos de crise,
quando a inflação se elevava. Isto era ainda agravado pelo êxodo rural. Com a
grande migração de pessoas do campo para as cidades, sem que estas tivessem
condições de planejamento para recebê-las, sobrava aos migrantes a ocupação de
terrenos urbanos sem infraestrutura adequada, muitas vezes em áreas de risco,
sem regras adequadas de urbanização, para construir moradias precárias, muitas
vezes provisórias, com materiais de baixíssima qualidade, dada a possibilidade
de remoção a que estavam sujeitos. Com as reformas da Economia brasileira desde
meados da década de 90, que estabalizaram a moeda, os motivos que levavam a
tendência de imobilização de capital na forma de terra e imóveis nos períodos de
crise econômica desapareceram. Outros fatores, no entanto, como a valorização 
das *commodities* agrícolas e a injeção de capital externo na economia
brasileira, no entanto, ocorrida pela abertura da economia brasileira aos
capitais externos, não deixaram que os preços das terras caíssem, como previa 
Rangel, o que, segundo ele, traria uma reforma agrária espontânea, através dos 
próprios mecanismos do mercado.

No capítulo \@ref(economia), mostrou-se o comportamento esperado do mercado
imobiliário numa Economia de livre mercado, com inflação controlada, como é a
Economia brasileira na atualidade. Nesta configuração, os preços dos imóveis
tendem a ser influenciados pelas taxas de juros, em razão inversa: quanto menor
as taxas de juros, mais valorizados devem se tornar os imóveis. 

De uma maneira,
a situação é similar à situação provocada pela alta inflação: em períodos de
crise, os bancos centrais tendem a abaixar as taxas de juros nominais, buscando
incentivar a retomada da economia. Contudo, em patamares extremamente baixos
pelos padrões históricos, mesmo diante de baixíssimas taxas de inflação, as
taxas de juros reais tendem a ficar negativas, o que implica, a exemplo do que
ocorria com as altas taxas de inflação vigentes durante o século XX, em erosão
monetária. Devido à erosão monetária, os preços dos imóveis tendem a elevar-se,
pelo aumento da demanda por imobilização do capital, dado que as oportunidades
de inversão nos outros setores da Economia são escassos, pela baixa demanda
agregada. Desta forma, pode-se dizer que a causa das crises habitacionais, como
aconteceu no Brasil no século XX, não é propriamente a inflação alta, como
assinalava Rangel [-@rangel], mas as taxas de juros reais baixas ou negativas a
que ela levava. Isto pode ocorrer, no entanto, tanto em cenários de taxas de
inflação relativamente altas, como ocorreu no século XX, tanto em cenários de
inflação moderada, porém com taxas de juros nominais relativamente baixas, como
é a atual realidade da economia mundial.

No capítulo \@ref(indices), mostrou-se que a imensa maioria dos índices de 
preços existentes possuem metodologia que os tornas insuficientes para um
completo diagnóstico do \gls{MI}. Com o método de vendas repetidas, 
utilizado pelo índice de preços de imóveis mais conhecido, de *Case e Shiller*, 
por exemplo, sequer é possível saber o nível de preços atual, mas apenas a 
variação dos níveis de preços em relação aos períodos anteriores. Com os índices 
de preços hedônicos é possível saber o nível médio de preços dos imóveis,
porém não se pode dizer, pela análise exclusiva destes níveis médios de preços, 
se o \gls{MI} encontra-se ou não em consonância com os fundamentos econômicos. 
Além disto, a não ser com os índices de preços hedônicos, não é possível separar
os valores dos imóveis dos valores da terra, o que, como se viu, é o ideal, haja
vista que há fortes evidências de que as bolhas são provocadas mais por conta de
uma sobrevalorização da terra do que por conta de eventuais aumentos dos custos
das construção.

Outro problema mostrado com a grande maioria dos índices de preços é que estes
refletem apenas o comportamento médio do mercado, o que, como foi visto, não
é suficiente para um diagnóstico completo do \gls{MI}.

Um índice de preços mais adequado para diagnosticar o \gls{MI}, portante, seria
um índice de preços de terras, ou ainda um índice de preços de imóveis hedônico
com o qual seja possível separar os preços da terra dos preços dos imóveis,
ajustado em quantis, para aferir o comportamento relativo dos preços das terras
*a priori* mais valorizadas e menos valorizadas. Um índice de preços assim
ajustado disponível seria o ideal para o monitoramento do comportamento do 
\gls{MI} no Brasil.

Não se pode dar ao luxo de esperar, contudo, a criação de um índice para que 
as políticas públicas passem a ser implementadas. Na impossibilidade de medição,
no entanto, as políticas devem ser desenhadas de maneira a evitar com que os
eventuais estímulos sejam transformados em menor *affordability*. 

No capítulo \@ref(crise2008) mostraram-se os efeitos deletérios que as finanças
desreguladas podem ter sobre o \gls{MI}, levando à padrões de *booms* seguidos
de *busts* neste mercado, o que acaba levando a problemas de inadimplência que
afetam os financiadores e/ou seguradores destes financiamentos. A esperada
atuação dos governos no sentido de salvar o sistema financeiro levam ao problema
do *moral hazard*, incentivando que o problema se repita. O salvamento do
sistema financeiro, no entanto, é feito com dinheiro público, que deveria ser
utilizado para socorrer os verdadeiros prejudicados pela crise 
financeiro-habitacional, *i.e.* os mutuários, e não os responsáveis pela crise, 
*i.e.* os financiadores, o que historicamente, infelizmente, não ocorre.

No capítulo \@ref(politicas) mostraram-se os principais equívocos das políticas
habitacionais anteriores e o que pode ser feito para estimular o \gls{MI} de
maneira responsável, com o máximo de eficiência possível. As antigas políticas
de grandes programas de construção de moradias devem ser substituídas por
políticas mais eficientes, que atuem do lado da demanda. A implementação destas
políticas, no entanto, tendem a aquecer o \gls{MI}. Deve-se cuidar, portanto,
para que  o aquecimento do \gls{MI} ocasionado pelo aumento da demanda tenha 
condições de ser absorvido pelo mercado de uma maneira mais elástica, evitando 
assim que ocorra a formação de bolhas especulativas, o que teria o efeito 
contrário ao desejado, ou seja, diminuiria o *affordability*. 

Assumindo-se que os custos de construção mantenham-se constantes, independente 
do aquecimento do \gls{MI}, a exemplo do que ocorreu nos EUA durante o período
de formação da última bolha imobiliária, pode-se controlar os preços dos imóveis
simplesmente através da disponibilização de terrenos para construções. A 
destinação de terras públicas para a execução de empreendimentos imobiliários 
para a baixa renda, portanto, está na ordem natural das coisas. Com a destinação
de terras públicas, a necessidade de financiamento fica reduzida. Além disto,
com a disponibilização de terras públicas para a construção de empreendimentos,
ou ainda com a disponibilização de terras públicas no mercado, a demanda por 
terra pode ser suavizada, impedindo a formação de bolhas.

---

Para isto, é necessária a articulação do governo federal com as administrações
municipais e estaduais, de maneira a favorecer a instalação de novos
loteamentos, com o necessário acompanhamento da infraestrutura urbana.           

Com a crise que lida atualmente a economia brasileira, está claro, ao menos
por enquanto, que o problema se inverteu: se os preços dos imóveis não caíram
em termos nominais, o fizeram em termos reais, através da corrosão de valor
inflacionária. As taxas de juros caíram consideravelmente no Brasil nos últimos
anos e junto com elas as taxas de inflação. A inflação não dá sinal que voltará
a galopar, apesar da liberação dos preços dos combustíveis e dos preços dos 
alimentos, cujos estoques reguladores estão zerados. A demanda é fraca e a 
capacidade ociosa instalada na Economia ainda é grande, razão pela qual os 
investimentos não tendem a aparecer tão cedo. No \gls{MI}, a tendência é que, se
muito, os investimentos voltem apenas voltados para a construção de imóveis para
as classes altas e média-altas, muitas vezes voltados para a concessão de 
serviços do tipo Airbnb ou quetais.

Conforme visto no capítulo \@ref(economia), existe uma correlação bidirecional
entre o aumento no preço dos imóveis com as taxas de inflação, o \gls{PIB} e
outras variáveis macroeconômicas. Numa situação como a atual, numa armadilha de
liquidez, é desejável que haja alguma pressão inflacionária, pois a inflação
deprime as taxas de juros reais, incentivando os investimentos na Economia como
um todo, não apenas no setor habitacional. Ou seja, não há momento melhor, em
termos macroeconômicos, do que o presente para a implantação de programas que
incentivem a demanda por imóveis.

Dado o grande déficit habitacional no Brasil, os investimentos devem ser
grandes, se os programas habitacionais forem bem dimensionados. O maior
investimento na construção de moradias tem o poder de puxar a demanda da
indústria da construção (cimento, siderúrgicas, cerâmicas, etc.), da indústria
leve (utensílios domésticos), do varejo (depósitos de construção, lojas de
eletrodomésticos), entre outras. Pelo lado da oferta, estes incentivos devem ser
acompanhados, é claro, com o investimento em infraestrutura urbana, visando
dissolver os pontos de estrangulamento do mercado. Com nova infraestrutura,
tem-se novos loteamentos e a oferta torna-se elástica. Também o setor de
infraestrutura tem um impacto na indústrica de materiais de construção. Do lado
fiscal, se o Governo Federal deverá ser o grande financiador do novo modelo, por
outro lado terá um adicional de arrecadação via efeito multiplicador dos
investimentos. Finalmente, o aumento do \gls{PIB} tenderá a compensar eventuais
déficits orçamentários, ajudando a equilibrar a relação Dívida/\gls{PIB}.

Pelo lado da oferta, o Brasil tem uma vantagem enorme em relação a outros países
para colocar em marcha o \gls{MI}: a quantidade de terra e imóveis da União por
todo o Brasil é significante, incluso as terras de marinha, muitas das quais já
contando com relevante infraestrutura urbana. É possível, desta maneira, quem
sabe, vencer um dos maiores obstáculos na política urbana hoje, que é a
concatenação dos esforços entre as diversas esferas da administração pública,
federal, estadual e municipal. cabe ao governo federal tomar a iniciativa,
exigindo contrapartidas dos estados e municípios na liberação dos terrenos de
marinha, buscando a viabilização dos empreendimentos de mais baixa renda, onde
a elasticidade da oferta do mercado tende a ser menor. A venda de terrenos de
marinha somente deveria ser feita com a contrapartida da execução de um 
empreendimento habitacional. Os preços de venda podem ser subsidiados (ou 
zerados) para os empreendimentos de baixa renda, viabilizando-os. Não faz sentido
o governo federal vender os terrenos de marinha para depois subsidiar os 
investimentos no \gls{PMCMV}, pois desta maneira estará subsidiando a compra da
terra que ele mesmo vendeu inicialmente. Com o menor preço da terra, mais
empreendimentos se viabilizam e/ou os imóveis construídos podem ter maior 
qualidade, melhorando a composição do estoque residencial, o que irá ser sentido
a longo prazo. Além disto, o *retrofit* dos imóveis construídos, como o célebre
Edifício "A Noite", transformando o seu uso, de comercial para residencial, 
tem o poder de aumentar a elasticidade da oferta de maneira muito rápida.

## Diretrizes para a implementação de políticas públicas para a habitação social

Políticas públicas devem ser traçadas no sentido de:

1. Controle de aluguéis dos imóveis existentes por um breve período de tempo, 
diminuindo assim o grau de especulação do sistema. Esta medida, por si só, deve
vir a ser necessária aqui, como tem se mostrado necessária no exterior, mas não 
é suficiente. Deverá vir acompanhada de medidas de estímulo à produção de novos
imóveis para a solução do déficit habitacional no longo prazo;

2. Para os novos empreendimentos urge considerar adotar medidas como as da
Inglaterra, como o estabelecimento de uma cota de habitações sociais. Estes
empreendimentos deverão ser localizados preferencialmente em regiões de
infraestrutura já consolidada. Para isto o poder pública municipal deverá
utilizar dos instrumentos de desapropriação, caso necessário;

3. Ao mesmo tempo, o poder público deve iniciar a busca de novas fontes de 
financiamento, através do bom uso dos instrumentos disponíveis previstos no
Estatuto da Cidade (IPTU progressivo, Contribuição de melhoria e outros). No 
entanto, acredita-se que apenas medidas sistêmicas e obrigatórias surtam
efeito. Deixar que a possibilidade de aplicação destas medidas a cargo das
municipalidades tende a inação pela lógica política local;

4. Os recursos advindos da aplicação destes instrumentos deve ter destinação
certa: deve ser estudado um marco legal para isto, que preveja que os recursos
arrecadados com estes instrumentos sejam revertidos para a atualização e
manutenção dos cadastros municipais, revisão de plantas de valores, criação de
bases de dados confiáveis de transações imobiliárias e aluguéis, confecção de
índices imobiliários que possibilitem a aferição do estoque de moradias e o
investimento em novas moradias, desapropriação de áreas para implantação de
empreendimentos para habitação social, etc;

5. Devem ser criadas empresas municipais de urbanização que reúna os melhores
engenheiros e arquitetos, que se especializem nas soluções adotadas por outros
países, como as cidades-jardim, as *new towns* e projetem conjuntos
habitacionais dentro de um contexto maior de urbanismo para que não se deteriore
facilmente, para que não se criem novos guetos;

6. Os empreendimentos devem vir acompanhados de infraestrutura pública, 
especialmente segurança e saneamento básico, para que se evite a propagação de 
novas epidemais;

## Objetivo 1

## Objetivo 2

## Objetivo 3

Os tempos que se aproximam são de uma tendência de queda brutal das taxas de
juros de longo prazo. Estas taxas apenas refletem uma imensa sobra de capital no
sistema, decorrente da falta de oportunidades de inversões em atividades
produtivas, o que tende a levar a eficácia marginal do capital a níveis muito
baixos, as vezes até negativos. As taxas de juros oficiais apenas refletem esta
realidade do mercado. Problemas como a armadilha de liquidez, antes restritos
aos países desenvolvidos, estão na ordem natural das coisas também para os
países emergentes [@krugman-emergentes].

Este capital abundante, sem oportunidades de inversão, tende a se procurar
reservas de valor, se alocando em grande parte no mercado imobiliário. Isto, por
si só já é um grande problema a ser resolvido, pois a tendência é que, como a
recessão econômica, novos empreendimentos não venham a surgir na mesma
velocidade de antes e os imóveis podem ficar parados por anos a espera de
oportunidades de inversão, tendo lugar apenas empreendimentos para as classes
mais altas, muito mais rentáveis. Porém, um problema ainda maior pode vir a
ocorrer com o enorme influxo de capital se movendo para o mercado imobiliário, a
saber, uma forte tendência de aumento dos preços. Esta possível tendência de
aumento dos preços pode vir a desencadear uma espiral de especulação
desenfreada, atraindo ainda mais capitais para o mercado imobiliário.

O problema destes juros muito baixos já se fez sentir nos países desenvolvidos,
onde o excesso de capitais teve papel principal na criação de bolhas
imobiliárias, como a do *subprime* norte-americano. Os principais prejudicados,
no final, são os mutuários, que perdem suas casas e suas poupanças, já que os
especuladores tendem a lucrar com a liquidação forçada dos imóveis,
revendendo-os depois de alguns anos com a recuperação dos preços, como foi 
observado. Mas mesmo após o estouro da bolha, a elevação dos preços dos imóveis 
se mostrou uma tendência nestes países e o resultado é que há crises 
habitacionais em praticamente todos os países, pela falta de habitação a preços
acessíveis.

Nos países em desenvolvimento, esta tendência ao aumento do preço da terra em
períodos de recessão econômica, já prevista por Rangel, tende somente a agravar
a crise habitacional crônica em que vivem o Brasil e outros países da \gls{AL}
há décadas.

Neste contexto, os instrumentos tradicionais de política urbana previstos no 
Estatuto da Cidade são insuficientes. Não quer isto dizer que sejam 
desnecessários. Muito pelo contrário: o que se necessita é de uma política 
de Estado que coloque em aplicação os diversos instrumentos previstos de maneira
coordenada, além da inclusão de outros instrumentos mais radicais não previstos,
dada a magnitude do problema.  

Esta política habitacional deve ser coordenada em torno de um objetivo, que é
a construção de habitação social. A implementação destas políticas não pode ser 
deixada a cargo de cada municipalidade: as administrações municipais devem ter
um papel de auxiliar na implantação da política habitacional, mas a coordenação
deve ser nacional, pois a lógica política local tende a abortar muitas 
iniciativas.

Por fim, uma nova política habitacional poderia trazer consigo o estabelecimento
de um novo ciclo de crescimento econômico, pois tem um grande potencial para a 
geração de empregos. Além disto, o investimento em habitação social pode vir a
diminuir os gastos sociais, pois melhora as condições de vida da população, e 
e reduzir também os gastos com a saúde pública, dada a melhora no saneamento 
básico para a população.

```{=latex}
\printbibliography[heading=subbibintoc]
\end{refsection}
```
