---
author: 'LUIZ FERNANDO PALIN DROUBI'
local: Florianópolis
date_year: '2020'
date_month: 'Março'
date_day: '31'
institution: 'Universidade Federal de Santa Catarina'
inst_short: 'UFSC'
division: 'CTC - CENTRO TECNOLÓGICO'
coordinator: Ana Maria Bencciveni Franzoni
advisor: Norberto Hochheim
# If you have more two advisors, un-silence line 7
#altadvisor: 'Your Other Advisor'
examiner:
- title: Prof.
  name: Everton da Silva
  degree: Dr.
  institution: Universidade Federal de Santa Catarina
  inst_short: UFSC
- title: Prof.
  name: Examinador 2
  degree: Dr.
  institution: Fédération Internationale des Géomètres
  inst_short: FIG
department: |
  Programa de Pós-Graduação em Engenharia de Transportes e Gestão Territorial
degree: 'Mestre em Engenharia de Transportes e Gestão Territorial'
level: 'mestrado'
doc_type: 'Dissertação'
title: 'O Mercado Imobiliário e a Economia'
subtitle: 'Qualificação'
knit: "bookdown::render_book"
site: bookdown::bookdown_site
output: 
  ufscdown::thesis_pdf:
    citation_package: biblatex
    bib_engine: biber
# ufscdown::thesis_gitbook: default
#  ufscdown::thesis_word: default
#  ufscdown::thesis_epub: default
# If you are creating a PDF you'll need to write your preliminary content (e.g., 
# abstract, acknowledgements) here or use code similar to line 43-44 for the 
# .RMD files. If you are NOT producing a PDF, you can delete or silence lines 
# 42-59 in this YAML header.
abstract: |
  `r if(knitr:::is_latex_output()) paste(readLines("00-abstract.Rmd"), 
  collapse = '\n  ')`
palavras-chave: [Mercado Imobiliário, Macroeconomia, Microeconomia]
foreignabstract: |
  `r if(knitr:::is_latex_output()) paste(readLines("00-foreignabstract.Rmd"), 
  collapse = '\n  ')`
# If you'd rather include the preliminary content in files instead of inline
# like below, use a command like that for the abstract above.  Note that a tab 
# is needed on the line after the `|`.
keyword: [Real Estate, Macroeconomics,  Microeconomics]
epigrafe: |
  | "Eppur si muove!"  
  | (Galileu Galilei, 1633)
# Specify the location of the bibliography below
bibliography: [bib/cap1.bib, bib/cap2.bib, bib/cap3.bib, bib/cap4.bib, bib/cap5.bib, bib/pkgs.bib]
# Download your specific csl file and refer to it in the line below.
link-citations: true
#biblio-style: abnt
#csl: csl/apa.csl
#lot: true
#lof: true
dedication: |
  À Bibi.
thanks: |
  | Gostaria de agradecer sinceramente a todos os que colaboraram à execução 
  | deste trabalho.
  | Aos colegas da UFSC.
  | Aos professores do PPGTG.
  | Em especial ao meu orientador, pela paciência.
  | E a minha querida esposa pela compreensão.
# If you prefer blank lines between paragraphs, un-silence lines  74-75 (this 
# requires package tikz)
#header-includes:
#- \usepackage{tikz}
---

<!--
Above is the YAML (YAML Ain't Markup Language) header that includes a lot of 
metadata used to produce the document.  Be careful with spacing in this header!

If you'd prefer to not include a Dedication, for example, simply delete the 
section entirely, or silence (add #) them. 

If you have other LaTeX packages you would like to include, delete the # 
before header-includes and list the packages after hyphens on new lines.

If you'd like to include a comment that won't be produced in your resulting file 
enclose it in a block like this.

If you receive a duplicate label error after knitting, make sure to delete the 
index.Rmd file and then knit again.
-->

```{r include_packages, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = FALSE, message=FALSE, warning = FALSE, 
                      fig.ext='png', fig.align='center', fig.path = "images/",
                      fig.pos = "H", dev = "png", dpi = 600, out.width = "70%")
type <- knitr::opts_knit$get("rmarkdown.pandoc.to")
# This chunk ensures that the ufscdown package is
# installed and loaded. This ufscdown package includes
# the template files for the thesis.
if(!require(remotes))
  install.packages("remotes", repos = "http://cran.rstudio.com")
if(!require(ufscdown))
  remotes::install_github("lfpdroubi/ufscdown")
library(ufscdown)
library(kableExtra)
library(tidyr)
library(dplyr)
library(ggplot2)
library(ggfortify)
library(ggpmisc)
library(scales)
library(cowplot)
theme_set(theme_cowplot(14))
library(YieldCurve)
library(ustyc)
library(Quandl)
Quandl.api_key("KFMsKFYU9QNph_XnbVUQ")
library(fredr)
fredr_set_key("8866e5606159b57dd69d9d8392ddfd1d")
library(BETS)
library(zoo)
library(appraiseR)
gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}
```

<!-- On ordering the chapter files:
There are two options:
1. Name your chapter files in the order in which you want them to appear (e.g., 
01-Intro, 02-Data, 03-Conclusions). 
2. Otherwise, you can specify the order in which they appear in the 
_bookdown.yml (for PDF only).

Do not include 00(two-hyphens)prelim.Rmd and 00-abstract.Rmd in the YAML file--
they are handled in the YAML above differently for the PDF version.
-->

<!-- The {.unnumbered} option here means that the introduction will be 
"Chapter 0." You can also use {-} for no numbers
on chapters.
-->

# Introdução {#intro}

## O conceito de terra e a importância do território

De acordo com @realestate, a terra é a base das atividades econômicas e sociais
de um povo, essencial para a vida e a sociedade, sendo assunto de diversas 
disciplinas, como o Direito, Economia, Finanças, Sociologia e a Geografia.

No Direito, a terra é abordada no direito de propriedade e uso social da terra.
Na Economia, a terra é considerada um dos fatores de produção, ao lado do
trabalho e do capital. Nas Finanças, a terra é considerada como um bem
suscetível de ser dado em garantia, em troca de capital financeiro, visando
propiciar o desenvolvimento. Na perspectiva da Sociologia, a terra é um bem
comum de todos, que deve ser utilizado com fins de obtenção de uma sociedade
melhor. Já a Geografia foca em descrever os elementos físicos da terra e as
atividades humanas das pessoas que as habitam.

A Engenharia de Avaliações se preocupa em reconhecer os atributos que atuam na
formação de valor dos bens imóveis, um conceito ligado à Economia. Para isto, os
Avaliadores devem entender o mercado no qual estes bens estão inseridos. É o
mercado que reflete a atitude dos atores econômicos em resposta às forças
sociais e econômicas e às restrições da lei e dos ônus legais [@realestate, 10].

## O Mercado Imobiliário

O mercado imobiliário urbano pode ser dividido basicamente em:

1. Mercado de imóveis residencias e;
2. Mercado de imóveis comerciais.

O Mercado Imobiliário se conecta à macroeconomia através:

1. Do setor de construção civil;
2. Da demanda agregada, já que existe uma conexão entre a propensão marginal
a consumir com o efeito riqueza do Mercado Imobiliário;
3. Do setor bancário, haja vista que os bancos possuem imóveis em seu portfolio,
seja através da propriedade, ou através do financiamento imobiliário e hipotecas.

